# Generated by Django 4.0.5 on 2022-06-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_alter_instruction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
