# Generated by Django 4.0.5 on 2022-06-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_instruction_user_alter_instruction_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='instruction_count',
        ),
    ]
