name: Quokkit Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    name: testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run tests
        run: |
          pipenv run coverage run --source='.' manage.py test */tests

      - name: Lint with flake8
        run: |
          pipenv run flake8

      - name: Print coverage report
        run: |
          pipenv run coverage report
